site_name: SOM
site_description: “Sufficiency of Measures Tool Documentation”
repo_url: https://github.com/helcomsecretariat/SOM
repo_name: helcomsecretariat/SOM
theme:
  name: material
  font:
    text: Roboto
  icon:
    repo: fontawesome/brands/git-alt
    logo: material/library-outline
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.top
    - toc.follow
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
      primary: custom
      accent: custom
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
      primary: custom
      accent: custom
extra_css:
  - stylesheets/extra.css
nav:
  - Home: 
    - Sufficiency of Measures: index.md
    - License: license.md
  - User Guide:
    - Welcome: guide/welcome.md
    - Installation: guide/installation.md
    - Using the tool: guide/using-the-tool.md
    - Using the UI: guide/using-the-gui.md
    - Configuration: guide/configuration.md
    - File structure: guide/file-structure.md
    - Input data: guide/input-data.md
    - Input data (legacy): guide/input-data-legacy.md
    - Linking areas: guide/linking-areas.md
    - Interpreting the results: guide/interpreting-the-results.md
  - API Reference:
    - main: modules/main.md
    - som_app: modules/som_app.md
    - som_tools: modules/som_tools.md
    - som_plots: modules/som_plots.md
    - utilities: modules/utilities.md
    - api_tools: modules/api_tools.md
  - Development:
    - Welcome: development/welcome.md
    - Documentation: development/documentation.md
    - Tool: development/tool.md
    - User interface: development/user-interface.md
    - Further development: development/further-development.md
plugins:
  - search
  - mkdocstrings:
      default_handler: python
      # handlers:
      #   python:
      #     paths: [src]
  - git-revision-date-localized:
      type: date
  - git-authors

copyright: Copyright &copy 2025 Baltic Marine Environment Protection Commission

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/helcomsecretariat  # link to HELCOM github account
  # generator: false  # hide the "Made with Material for MkDocs" footer