# Configuration file

# export path
export_path = './protect_baltic/src/data/results.xlsx'

# scenario used for calculations
use_scenario = false
scenario = 'ChangeML'

# randomness setup
use_random_seed = true
random_seed = 10022025

# number of simulations
simulations = 10

# performance options
use_parallel_processing = true

# excel input files
use_legacy_input_data = false
[input_data]
    path = './protect_baltic/src/data/input_data.xlsx'
[input_data_legacy]
    general_input = './protect_baltic/src/data/generalInput.xlsx'
    measure_effect_input = './protect_baltic/src/data/measureEffectInput.xlsx'
    pressure_state_input = './protect_baltic/src/data/pressureStateInput.xlsx'
    [input_data_legacy.general_input_sheets]
        case = 'ActMeas'
        postprocess = 'ActPres'
        overlaps = 'Overlaps'
        development_scenarios = 'DEV_scenarios'
        subpressures = 'SubPres'
        [input_data_legacy.general_input_sheets.ID]
            measure = 'Measure ID'
            activity = 'Activity ID'
            pressure = 'Pressure ID'
            state = 'State ID'
            area = 'Area ID'

# filter selection for results, include all if empty
[filter]
    area = []
    measure = []
    activity = []
    pressure = []
    state = []
