# Configuration file

# export path
export_path = './data/example/exampleResults.xlsx'

# scenario used for calculations
use_scenario = false
scenario = 'ChangeML'

# randomness setup
use_random_seed = true
random_seed = 10022025

# number of simulations
simulations = 10

# excel input files
use_legacy_input_data = false
[input_data]
    path = './data/example/exampleInputData.xlsx'
[input_data_legacy]
    general_input = './data/example/exampleData.xlsx'
    measure_effect_input = './data/example/exampleEffect.xlsx'
    pressure_state_input = './data/example/examplePressureState.xlsx'
    [input_data_legacy.general_input_sheets]
        case = 'ActMeas'
        postprocess = 'ActPres'
        overlaps = 'Overlaps'
        development_scenarios = 'DEV_scenarios'
        subpressures = 'SubPres'
        [input_data_legacy.general_input_sheets.ID]
            measure = 'Measure ID'
            activity = 'Activity ID'
            pressure = 'Pressure ID'
            state = 'State ID'
            area = 'Area ID'
