# Configuration file

# Excel input files
[input_files]
    general_input = 'data/generalInput.xlsx'
    measure_effect_input = 'data/measureEffInput.xlsx'
    pressure_state_input = 'data/pressStateInput.xlsx'


# sheet indexes and names in input files
# indexes are converted to integers
[measure_survey_sheets]
    0 = 'MTEQ'
    1 = 'MT_surv_Benthic'
    2 = 'MT_surv_Birds'
    3 = 'MT_surv_Fish'
    4 = 'MT_surv_HZ'
    5 = 'MT_surv_NIS'
    6 = 'MT_surv_Noise'
    7 = 'MT_surv_Mammals'
