# Configuration file

# excel input files
[input_files]
    general_input = '/Data/generalInput.xlsx'
    measure_effect_input = '/Data/measureEffInput.xlsx'
    pressure_state_input = '/Data/pressStateInput.xlsx'


# sheet indexes and names in input files
# indexes are converted to integers
[measure_survey_sheets]
    0 = 'MTEQ'
    1 = 'MT_surv_Benthic'
    2 = 'MT_surv_Birds'
    3 = 'MT_surv_Fish'
    4 = 'MT_surv_HZ'
    5 = 'MT_surv_NIS'
    6 = 'MT_surv_Noise'
    7 = 'MT_surv_Mammals'

[pressure_survey_sheets]
    0 = 'PSQ'
    1 = 'PS_surv_Benthic'
    2 = 'PS_surv_Birds'
    3 = 'PS_surv_Fish_Migratory'
    4 = 'PS_surv_Fish_Coastal'
    5 = 'PS_surv_Fish_Commercial'
    6 = 'PS_surv_HZ'
    7 = 'PS_surv_Mammals'

[general_input_sheets]
    [general_input_sheets.ID]
        measure = 'Measure ID'
        activity = 'Activity ID'
        pressure = 'Pressure ID'
        state = 'State ID'
    [general_input_sheets.domain]
        basin = 'Basin ID'
        country = 'Country ID'
        countries_by_basins = 'CountBas'


# countries to exclude from domain
[domain_settings]
    countries_exclude = ['All countries', 'Global (non-Baltic)']
    basins_exclude = ['All basins']
