# Configuration file

####################################

# export path
export_path = './src/data/results.xlsx'

# scenario used for calculations
use_scenario = false
scenario = 'BAU'

# randomness setup
use_random_seed = true
random_seed = 10022025

# number of simulations
simulations = 10

# performance options
use_parallel_processing = true

# plot results
create_plots = true

####################################

# excel input files
use_legacy_input_data = false
[input_data]
    path = './src/data/input_data.xlsx'
[input_data_legacy]
    general_input = './src/data/generalInput.xlsx'
    measure_effect_input = './src/data/measureEffectInput.xlsx'
    pressure_state_input = './src/data/pressureStateInput.xlsx'
    [input_data_legacy.general_input_sheets]
        case = 'ActMeas'
        postprocess = 'ActPres'
        overlaps = 'Overlaps'
        development_scenarios = 'DEV_scenarios'
        subpressures = 'SubPres'
        [input_data_legacy.general_input_sheets.ID]
            measure = 'Measure ID'
            activity = 'Activity ID'
            pressure = 'Pressure ID'
            state = 'State ID'
            area = 'Area ID'

####################################

# filter selection for results, include all if empty
[filter]
    area = []
    measure = []
    activity = []
    pressure = []
    state = []

####################################

link_mpas_to_subbasins = false

# used by the helcom api for linking MPAs to subbasins
[layers]

    [layers.subbasin]
    url = ""
    path = "data/layers/subbasins_by_country/subbasins_by_country.shp"
    id_attr = "OBJECTID"

    [layers.mpa]
    url = "https://maps.helcom.fi/arcgis/rest/services/MADS/Biodiversity/MapServer/54/query?where=1%3D1&outFields=%2A&f=geoJSON"
    path = "data/layers/mpas/mpas.shp"
    measure_attr = "Measures"
    id_attr = "MPA_ID"
    name_attr = "Name"
    measure_delimiter = ";"
